// examples/vue-kitchen-sink/src/stories/Counter.vue
<template>
  <div>
    <h1>Vue - Counter</h1>
    <h2 data-testid="count">You clicked {{count}} times</h2>
    <button type="button" @click="decrement">Decrement</button>
    <button type="button" @click="increment">Increment</button>
  </div>
</template>

<script>
export default {
  name: 'Counter',
  data() {
    return { count: 0 };
  },
  methods: {
    increment() {
      this.count++;
    },
    decrement() {
      this.count--;
    },
  },
};
</script>

// examples/svelte-kitchen-sink/src/components/Counter.svelte
<script lang="ts">
  export let count = 0;

  function onIncrement() {
    count +=1 
  }

  function onDecrement() {
    count +=1 
  }
</script>

<div>
  <h1>Svelte - Counter</h1>
  <h2 data-testid="count">You clicked {count} times</h2>
  <button type="button" on:click={onDecrement}>Decrement</button>
  <button type="button" on:click={onIncrement}>Increment</button>
</div>
