// app/react/src/client/preview/types.ts
import { ReactElement } from 'react';

export type { RenderContext } from '@storybook/store';
export type { StoryContext } from '@storybook/csf';

export interface ShowErrorArgs {
  title: string;
  description: string;
}

export type StoryFnReactReturnType = ReactElement<unknown>;

export interface IStorybookStory {
  name: string;
  render: () => any;
}

export interface IStorybookSection {
  kind: string;
  stories: IStorybookStory[];
}

// app/lit/src/client/preview/types.ts
import { TemplateResult, SVGTemplateResult } from 'lit';

export type { RenderContext } from '@storybook/core';
export type { Args, ArgTypes, Parameters, StoryContext } from '@storybook/addons';

export type StoryFnLitReturnType = string | Node | TemplateResult | SVGTemplateResult;

export interface IStorybookStory {
  name: string;
  render: () => any;
}

export interface IStorybookSection {
  kind: string;
  stories: IStorybookStory[];
}

export interface ShowErrorArgs {
  title: string;
  description: string;
}
